---
  - name: Configure Instance
    hosts: launched
    remote_user: ec2-user
    tasks:
    - name: curl to get public ip
      shell: "curl ident.me"
      register: host
    - name: set hostname as environment variable
      shell: export HOST="{{ host.stdout }}"
    - name: Add host to bashrc
      lineinfile: dest=~/.bashrc line='export HOST={{ host.stdout }}' insertafter='EOF' state=present
    - name: set slack_token as environment variable
      shell: export SLACK_TOKEN="{{ SLACK_TOKEN }}"
    - name: Add slack_token to bashrc
      lineinfile: dest=~/.bashrc line='export SLACK_TOKEN={{ SLACK_TOKEN }}' insertafter='EOF' state=present
    - name: set port as environment variable
      shell: export PORT="{{ PORT }}"
    - name: Add port to bashrc
      lineinfile: dest=~/.bashrc line='export PORT={{ PORT }}' insertafter='EOF' state=present
    - name: "Download Repo"
      yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm state=present
      become: true
    - name: Download the dependencies
      yum: name={{item}} state=present
      with_items:
       - npm
       - git
      become: true
    - name: Install redis
      script: install_redis.sh
    - name: Download the project from git
      git: repo=http://www.github.com/rahulpshah/DockrRockr.git dest=~/DockrRockr
    - name: Install forever
      npm: name=forever global=yes state=present
      become: true
    - name: Install project dependencies
      npm: path=~/DockrRockr/
    - name: Start Redis
      command: /usr/bin/redis-server
      ignore_errors: yes
      async: 45
      poll: 0
    - name: start DockrRockr
      command: forever start index.js chdir=~/DockrRockr 
      async: 45
      poll: 0