---
- hosts: all
  vars:
      slack_token: "{{ lookup('env','SLACK_TOKEN') }}"
  tasks:
    - name: "Download Repo"
      yum: name=http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm state=present
      become: true
    - name: Download the dependencies
      yum: name={{item}} state=present  
      with_items:
       - npm
       - git
       - redis
      become: true
    - name: Download the project from git
      git: repo=http://www.github.com/rahulpshah/DockrRockr.git dest=~/DockrRockr
    - name: Install forever
      npm: name=forever global=yes state=present
      become: true
    - name: Install project dependencies
      npm: path=~/DockrRockr/
    - name: Start Redis
      command: /usr/bin/redis-server
      ignore_errors: yes
      async: 45
      poll: 0
    - name: start DockrRockr
      command: forever index.js chdir=~/DockrRockr
      async: 45
      poll: 0
      
       

